{% set name = "wntr" %}
{% set version = "v0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/USEPA/WNTR/archive/0.5.0.zip
  sha256: 21bb1fde619094e550e9fec338feb3f78268596f8a9db7cace69aa4c216ca216

build:
  number: 1
  script_env:
    - BUILD_WNTR_EXTENSIONS="true"
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('cxx') }}
    - python
    - pip
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - networkx
    - pandas
    - scipy
    - matplotlib-base

test:
  imports:
    - wntr
  requires:
    - nose
    - plotly
    - folium
    - utm
    - openpyxl
    - matplotlib
  commands:
    - nosetests -v wntr.tests.test_network_controls
    - nosetests -v wntr.tests.test_network_valves

about:
  home: https://github.com/USEPA/WNTR
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: 'Water Network Tool for Resilience'

extra:
  recipe-maintainers:
    - michaelbynum
    - kaklise
