{% set name = "wntr" %}
{% set version = "1.4.0rc1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/USEPA/WNTR/archive/1.4.0rc1.zip
  sha256: aa31f5c1a383203cf1b2212bb462195f792efacc5c2ace184dd247ed11fa077b

build:
  number: 0
  script_env:
    - BUILD_WNTR_EXTENSIONS="true"
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - python
    - pip
  host:
    - python
    - pip
    - numpy
    - setuptools
  run:
    - python
    - {{ pin_compatible('numpy', lower_bound='2.2.6 ') }}
    - networkx
    - pandas
    - scipy
    - matplotlib-base
    - setuptools

test:
  imports:
    - wntr
  requires:
    - pytest
    - {{ pin_compatible('plotly', upper_bound='6.0') }}
    - folium
    - utm
    - openpyxl
    - matplotlib
    - setuptools
    - geopandas
    - rasterio
    - rtree
  commands:
    - pytest --pyargs wntr.tests.test_network_controls
    - pytest --pyargs wntr.tests.test_network_valves

about:
  home: https://github.com/USEPA/WNTR
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: 'Water Network Tool for Resilience'

extra:
  recipe-maintainers:
    - kbonney
    - michaelbynum
    - kaklise
    - dbhart
