{% set name = "wntr" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/USEPA/WNTR/archive/1.3.2.zip
  sha256: d4155b5d1130417b6137390bdfe47c1e5b0c4a34ef7141082bf7f810744b331d

build:
  number: 0
  script_env:
    - BUILD_WNTR_EXTENSIONS="true"
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - python
    - pip
  host:
    - python
    - pip
    - numpy
    - setuptools
  run:
    - python
    - {{ pin_compatible('numpy', lower_bound='1.21', upper_bound='2.0') }}
    - {{ pin_compatible('scipy', upper_bound='1.13') }}
    - networkx
    - pandas
    - matplotlib-base
    - setuptools

test:
  imports:
    - wntr
  requires:
    - pytest
    - {{ pin_compatible('plotly', upper_bound='6.0') }}
    - folium
    - utm
    - openpyxl
    - matplotlib
    - setuptools
    - {{ pin_compatible('geopandas', upper_bound='1.0') }}
    - {{ pin_compatible('fiona', upper_bound='1.10') }}
    - rasterio
    - rtree
  commands:
    - pytest --pyargs wntr.tests.test_network_controls
    - pytest --pyargs wntr.tests.test_network_valves

about:
  home: https://github.com/USEPA/WNTR
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: 'Water Network Tool for Resilience'

extra:
  recipe-maintainers:
    - kbonney
    - michaelbynum
    - kaklise
    - dbhart
