{% set name = "wntr" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/USEPA/WNTR/archive/1.3.0.zip
  sha256: 78aa135219cd45685a8377a2e4d77d57e44c8354616df969b933c1d8bf971b24

build:
  number: 0
  script_env:
    - BUILD_WNTR_EXTENSIONS="true"
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - python
    - pip
  host:
    - python
    - pip
    - numpy
    - setuptools
  run:
    - python
    - {{ pin_compatible('numpy', lower_bound='1.21', upper_bound='2.0') }}
    - {{ pin_compatible('scipy', upper_bound='1.13') }}
    - networkx
    - pandas
    - matplotlib-base
    - setuptools

test:
  imports:
    - wntr
  requires:
    - pytest
    - plotly
    - folium
    - utm
    - openpyxl
    - {{ pin_compatible('geopandas', upper_bound='1.0') }}
    - {{ pin_compatible('fiona', upper_bound='1.10') }}
    - rasterio
    - rtree
    - matplotlib
    - setuptools
  commands:
    - pytest --pyargs wntr.tests.test_network_controls
    - pytest --pyargs wntr.tests.test_network_valves

about:
  home: https://github.com/USEPA/WNTR
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: 'Water Network Tool for Resilience'

extra:
  recipe-maintainers:
    - michaelbynum
    - kaklise
