{% set name = "wntr" %}
{% set version = "0.2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/USEPA/WNTR/archive/0.2.2.1.zip
  sha256: 60e1fd15bd4c59878c4ac8f8895109c96fba924825610becc23176c370bb1a3e

build:
  number: 0
  skip: true  # [py<35]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('cxx') }}
    - python
    - pip
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - networkx
    - pandas
    - scipy
    - matplotlib-base

test:
  imports:
    - wntr

about:
  home: https://github.com/USEPA/WNTR
  license: Revised BSD
  license_family: BSD
  license_file: LICENSE.md
  summary: 'Water Network Tool for Resilience'

extra:
  recipe-maintainers:
    - michaelbynum
    - kaklise
