{% set name = "wntr" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/USEPA/WNTR/archive/{{ version }}.zip
  sha256: a2a97d575344057810ec4bda675babf6c878ee8a456dc49a6bbc5e59e458e101

build:
  number: 0
  script_env:
    - BUILD_WNTR_EXTENSIONS="true"
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - python
    - pip
  host:
    - python
    - pip
    - numpy
    - setuptools
  run:
    - python
    - {{ pin_compatible('numpy', lower_bound='2.2.6 ') }}
    - networkx
    - pandas
    - scipy
    - matplotlib-base
    - setuptools

test:
  imports:
    - wntr
  source_files:
    - wntr/tests/
  requires:
    - pytest
    - {{ pin_compatible('plotly', upper_bound='6.0') }}
    - folium
    - utm
    - openpyxl
    - matplotlib
    - setuptools
    - geopandas
    - rasterio
    - rtree
  commands:
    - pytest wntr/tests/test_network_controls.py
    - pytest wntr/tests/test_network_valves.py

about:
  home: https://github.com/USEPA/WNTR
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: 'Water Network Tool for Resilience'

extra:
  recipe-maintainers:
    - kbonney
    - michaelbynum
    - kaklise
    - dbhart
