{% set name = "wntr" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/USEPA/WNTR/archive/0.4.0.zip
  sha256: 1479bd35e72e60ba729ce6867082d04323cc6280b27aa098c7f946bd6502f4e9

build:
  number: 0
  skip: true  # [py<35]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('cxx') }}
    - python
    - pip
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - networkx
    - pandas
    - scipy
    - matplotlib-base

test:
  imports:
    - wntr
  requires:
    - nose
    - plotly
    - folium
    - utm
    - openpyxl
    - matplotlib
  commands:
    - nosetests -v wntr

about:
  home: https://github.com/USEPA/WNTR
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: 'Water Network Tool for Resilience'

extra:
  recipe-maintainers:
    - michaelbynum
    - kaklise
