{% set name = "wntr" %}
{% set version = "v1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/USEPA/WNTR/archive/1.2.0.zip
  sha256: 7230b5210d3e76d18633a385d4b65f166d6241efcd12bb805ba475936eeb8d67

build:
  number: 0
  script_env:
    - BUILD_WNTR_EXTENSIONS="true"
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('cxx') }}
    - python
    - pip
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy', lower_bound='1.21', upper_bound='2.0') }}
    - networkx
    - pandas
    - scipy
    - matplotlib-base
    - setuptools

test:
  imports:
    - wntr
  requires:
    - pytest
    - plotly
    - folium
    - utm
    - openpyxl
    - matplotlib
    - setuptools
  commands:
    - pytest --pyargs wntr.tests.test_network_controls
    - pytest --pyargs wntr.tests.test_network_valves

about:
  home: https://github.com/USEPA/WNTR
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: 'Water Network Tool for Resilience'

extra:
  recipe-maintainers:
    - kbonney
    - michaelbynum
    - kaklise
