appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: UZi3yLQ/OQxGUCjkNc/sRWsK5xSs6C0IoV74DKFFrhEWqtFZSN+8NKSaziNQLH5nkza4i2zzz1HDXrPZJ6Rp6izDFC0Susurnb3yaICCHasXYpkD937uF1fvBMCnJvrXI2NZV+ib58YCpr6g7YzYrEDVNgsekaJv9vTI/ZcgrRAFzzoiBTnrLIEdCkwKXn0Bc+tc9XlYaLvoAi/elsN+MyUlRJBAELwnO0ZoXPqpKnd4LJTN836n8XLADyqq+dNCPHZ57ACiNPx20WbP4I/uNgcn4Ou3burymTSZWKIV90aD11XUdDq5KVR+SrkUKcpEz7WNDPTYMdenU8J95U0StlNVnKSXPdCuRwgFj71cEYOcOZ/eWJwbUPJGfM8G+ERA9ryjsONOpLrW/4EXI/lYUR6wBdUGPbM4W1bhDzMeO9O4Zalmi24IbML4qZBDpNLfWkXs1qVmJNYLcn9gJBAl1gJrAVGSvM754Mj9nrN1Yh81L7Wjm7x0ykTGJNGqzmYTHdJ7LmqKO8ovK+h+P5xtUJDENKIWNZiw3XpJkTR0jA3rFMTEsZHrMA2QfvbtEFOQ47eWylQ/y6fNBEuGTmZeCF8VBqmt+F269AmQ9WHilUx9YC1v/bEPUUHFRUCJ2vGOdtFvtgeDR+h4ac4sYvQTOB+3rRzyx8Ez8F3KuLqWtHA=}
provider:
  win: azure
